name: Test Ephemeral Runner

on:
  workflow_dispatch: # Allows you to trigger this manually with a button click

jobs:
  test-job:
    runs-on: [self-hosted, gcp-ephemeral]
    steps:
      - name: Hello World
        run: echo "The ephemeral runner works!"
